spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: com.logistics.events


  mail:
    host: smtp.gmail.com
    port: 587
    username: vladking574@gmail.com

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

