server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      httpserver:
        max-header-size: 16KB


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
